// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: webvitals/scribe-web-vitals.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScribeWebVitals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedAt    string                 `protobuf:"bytes,1,opt,name=receivedAt,proto3" json:"receivedAt,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Akamai        *Akamai                `protobuf:"bytes,3,opt,name=akamai,proto3" json:"akamai,omitempty"`
	WebVitals     *WebVitals             `protobuf:"bytes,4,opt,name=webVitals,proto3" json:"webVitals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScribeWebVitals) Reset() {
	*x = ScribeWebVitals{}
	mi := &file_webvitals_scribe_web_vitals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScribeWebVitals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScribeWebVitals) ProtoMessage() {}

func (x *ScribeWebVitals) ProtoReflect() protoreflect.Message {
	mi := &file_webvitals_scribe_web_vitals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScribeWebVitals.ProtoReflect.Descriptor instead.
func (*ScribeWebVitals) Descriptor() ([]byte, []int) {
	return file_webvitals_scribe_web_vitals_proto_rawDescGZIP(), []int{0}
}

func (x *ScribeWebVitals) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *ScribeWebVitals) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ScribeWebVitals) GetAkamai() *Akamai {
	if x != nil {
		return x.Akamai
	}
	return nil
}

func (x *ScribeWebVitals) GetWebVitals() *WebVitals {
	if x != nil {
		return x.WebVitals
	}
	return nil
}

var File_webvitals_scribe_web_vitals_proto protoreflect.FileDescriptor

const file_webvitals_scribe_web_vitals_proto_rawDesc = "" +
	"\n" +
	"!webvitals/scribe-web-vitals.proto\x1a\x1awebvitals/web-vitals.proto\x1a\x18events/akamai-info.proto\"\x8c\x01\n" +
	"\x0fScribeWebVitals\x12\x1e\n" +
	"\n" +
	"receivedAt\x18\x01 \x01(\tR\n" +
	"receivedAt\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1f\n" +
	"\x06akamai\x18\x03 \x01(\v2\a.AkamaiR\x06akamai\x12(\n" +
	"\twebVitals\x18\x04 \x01(\v2\n" +
	".WebVitalsR\twebVitalsB@\n" +
	"\x1ccom.hifx.lens.webvitals.newsB\x14ScribeWebVitalsProtoZ\n" +
	".;protobufb\x06proto3"

var (
	file_webvitals_scribe_web_vitals_proto_rawDescOnce sync.Once
	file_webvitals_scribe_web_vitals_proto_rawDescData []byte
)

func file_webvitals_scribe_web_vitals_proto_rawDescGZIP() []byte {
	file_webvitals_scribe_web_vitals_proto_rawDescOnce.Do(func() {
		file_webvitals_scribe_web_vitals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webvitals_scribe_web_vitals_proto_rawDesc), len(file_webvitals_scribe_web_vitals_proto_rawDesc)))
	})
	return file_webvitals_scribe_web_vitals_proto_rawDescData
}

var file_webvitals_scribe_web_vitals_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_webvitals_scribe_web_vitals_proto_goTypes = []any{
	(*ScribeWebVitals)(nil), // 0: ScribeWebVitals
	(*Akamai)(nil),          // 1: Akamai
	(*WebVitals)(nil),       // 2: WebVitals
}
var file_webvitals_scribe_web_vitals_proto_depIdxs = []int32{
	1, // 0: ScribeWebVitals.akamai:type_name -> Akamai
	2, // 1: ScribeWebVitals.webVitals:type_name -> WebVitals
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_webvitals_scribe_web_vitals_proto_init() }
func file_webvitals_scribe_web_vitals_proto_init() {
	if File_webvitals_scribe_web_vitals_proto != nil {
		return
	}
	file_webvitals_web_vitals_proto_init()
	file_events_akamai_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webvitals_scribe_web_vitals_proto_rawDesc), len(file_webvitals_scribe_web_vitals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webvitals_scribe_web_vitals_proto_goTypes,
		DependencyIndexes: file_webvitals_scribe_web_vitals_proto_depIdxs,
		MessageInfos:      file_webvitals_scribe_web_vitals_proto_msgTypes,
	}.Build()
	File_webvitals_scribe_web_vitals_proto = out.File
	file_webvitals_scribe_web_vitals_proto_goTypes = nil
	file_webvitals_scribe_web_vitals_proto_depIdxs = nil
}
