// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: webvitals/web-vitals.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main message containing context, user, and events
type WebVitals struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SentAt         string                 `protobuf:"bytes,1,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	TrackerVersion string                 `protobuf:"bytes,2,opt,name=trackerVersion,proto3" json:"trackerVersion,omitempty"`
	Ctx            *Context               `protobuf:"bytes,3,opt,name=ctx,proto3" json:"ctx,omitempty"`   // imported field type
	User           *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"` // imported field type
	Events         []*Event               `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebVitals) Reset() {
	*x = WebVitals{}
	mi := &file_webvitals_web_vitals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebVitals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebVitals) ProtoMessage() {}

func (x *WebVitals) ProtoReflect() protoreflect.Message {
	mi := &file_webvitals_web_vitals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebVitals.ProtoReflect.Descriptor instead.
func (*WebVitals) Descriptor() ([]byte, []int) {
	return file_webvitals_web_vitals_proto_rawDescGZIP(), []int{0}
}

func (x *WebVitals) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *WebVitals) GetTrackerVersion() string {
	if x != nil {
		return x.TrackerVersion
	}
	return ""
}

func (x *WebVitals) GetCtx() *Context {
	if x != nil {
		return x.Ctx
	}
	return nil
}

func (x *WebVitals) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebVitals) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Event data for Web Vitals
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"` //required
	EventType     string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          *Data                  `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Page          *Page                  `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"` // imported filed type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_webvitals_web_vitals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_webvitals_web_vitals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_webvitals_web_vitals_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Event) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Rating        string                 `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Element       *Element               `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_webvitals_web_vitals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_webvitals_web_vitals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_webvitals_web_vitals_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Data) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *Data) GetElement() *Element {
	if x != nil {
		return x.Element
	}
	return nil
}

type Element struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	StartTime      float32                `protobuf:"fixed32,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	RenderTime     float32                `protobuf:"fixed32,3,opt,name=renderTime,proto3" json:"renderTime,omitempty"`
	LoadTime       float32                `protobuf:"fixed32,4,opt,name=loadTime,proto3" json:"loadTime,omitempty"`
	ElementTagName string                 `protobuf:"bytes,5,opt,name=elementTagName,proto3" json:"elementTagName,omitempty"`
	ElementId      string                 `protobuf:"bytes,6,opt,name=elementId,proto3" json:"elementId,omitempty"`
	ElementClasses string                 `protobuf:"bytes,7,opt,name=elementClasses,proto3" json:"elementClasses,omitempty"`
	Size           int32                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_webvitals_web_vitals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_webvitals_web_vitals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_webvitals_web_vitals_proto_rawDescGZIP(), []int{3}
}

func (x *Element) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Element) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Element) GetRenderTime() float32 {
	if x != nil {
		return x.RenderTime
	}
	return 0
}

func (x *Element) GetLoadTime() float32 {
	if x != nil {
		return x.LoadTime
	}
	return 0
}

func (x *Element) GetElementTagName() string {
	if x != nil {
		return x.ElementTagName
	}
	return ""
}

func (x *Element) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *Element) GetElementClasses() string {
	if x != nil {
		return x.ElementClasses
	}
	return ""
}

func (x *Element) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_webvitals_web_vitals_proto protoreflect.FileDescriptor

const file_webvitals_web_vitals_proto_rawDesc = "" +
	"\n" +
	"\x1awebvitals/web-vitals.proto\x1a\x14events/context.proto\x1a\x11events/user.proto\x1a\x11events/page.proto\"\xa2\x01\n" +
	"\tWebVitals\x12\x16\n" +
	"\x06sentAt\x18\x01 \x01(\tR\x06sentAt\x12&\n" +
	"\x0etrackerVersion\x18\x02 \x01(\tR\x0etrackerVersion\x12\x1a\n" +
	"\x03ctx\x18\x03 \x01(\v2\b.ContextR\x03ctx\x12\x19\n" +
	"\x04user\x18\x04 \x01(\v2\x05.UserR\x04user\x12\x1e\n" +
	"\x06events\x18\x05 \x03(\v2\x06.EventR\x06events\"\xb1\x01\n" +
	"\x05Event\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\teventName\x18\x02 \x01(\tR\teventName\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x19\n" +
	"\x04data\x18\x05 \x01(\v2\x05.DataR\x04data\x12\x19\n" +
	"\x04page\x18\x06 \x01(\v2\x05.PageR\x04page\"X\n" +
	"\x04Data\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\tR\x06rating\x12\"\n" +
	"\aelement\x18\x03 \x01(\v2\b.ElementR\aelement\"\xf7\x01\n" +
	"\aElement\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\x02R\tstartTime\x12\x1e\n" +
	"\n" +
	"renderTime\x18\x03 \x01(\x02R\n" +
	"renderTime\x12\x1a\n" +
	"\bloadTime\x18\x04 \x01(\x02R\bloadTime\x12&\n" +
	"\x0eelementTagName\x18\x05 \x01(\tR\x0eelementTagName\x12\x1c\n" +
	"\telementId\x18\x06 \x01(\tR\telementId\x12&\n" +
	"\x0eelementClasses\x18\a \x01(\tR\x0eelementClasses\x12\x12\n" +
	"\x04size\x18\b \x01(\x05R\x04sizeB:\n" +
	"\x1ccom.hifx.lens.webvitals.newsB\x0eWebVitalsProtoZ\n" +
	".;protobufb\x06proto3"

var (
	file_webvitals_web_vitals_proto_rawDescOnce sync.Once
	file_webvitals_web_vitals_proto_rawDescData []byte
)

func file_webvitals_web_vitals_proto_rawDescGZIP() []byte {
	file_webvitals_web_vitals_proto_rawDescOnce.Do(func() {
		file_webvitals_web_vitals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webvitals_web_vitals_proto_rawDesc), len(file_webvitals_web_vitals_proto_rawDesc)))
	})
	return file_webvitals_web_vitals_proto_rawDescData
}

var file_webvitals_web_vitals_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_webvitals_web_vitals_proto_goTypes = []any{
	(*WebVitals)(nil), // 0: WebVitals
	(*Event)(nil),     // 1: Event
	(*Data)(nil),      // 2: Data
	(*Element)(nil),   // 3: Element
	(*Context)(nil),   // 4: Context
	(*User)(nil),      // 5: User
	(*Page)(nil),      // 6: Page
}
var file_webvitals_web_vitals_proto_depIdxs = []int32{
	4, // 0: WebVitals.ctx:type_name -> Context
	5, // 1: WebVitals.user:type_name -> User
	1, // 2: WebVitals.events:type_name -> Event
	2, // 3: Event.data:type_name -> Data
	6, // 4: Event.page:type_name -> Page
	3, // 5: Data.element:type_name -> Element
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_webvitals_web_vitals_proto_init() }
func file_webvitals_web_vitals_proto_init() {
	if File_webvitals_web_vitals_proto != nil {
		return
	}
	file_events_context_proto_init()
	file_events_user_proto_init()
	file_events_page_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webvitals_web_vitals_proto_rawDesc), len(file_webvitals_web_vitals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webvitals_web_vitals_proto_goTypes,
		DependencyIndexes: file_webvitals_web_vitals_proto_depIdxs,
		MessageInfos:      file_webvitals_web_vitals_proto_msgTypes,
	}.Build()
	File_webvitals_web_vitals_proto = out.File
	file_webvitals_web_vitals_proto_goTypes = nil
	file_webvitals_web_vitals_proto_depIdxs = nil
}
