// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: events/akamai-info.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Akamai struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Akamai) Reset() {
	*x = Akamai{}
	mi := &file_events_akamai_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Akamai) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Akamai) ProtoMessage() {}

func (x *Akamai) ProtoReflect() protoreflect.Message {
	mi := &file_events_akamai_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Akamai.ProtoReflect.Descriptor instead.
func (*Akamai) Descriptor() ([]byte, []int) {
	return file_events_akamai_info_proto_rawDescGZIP(), []int{0}
}

func (x *Akamai) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Akamai) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

var File_events_akamai_info_proto protoreflect.FileDescriptor

const file_events_akamai_info_proto_rawDesc = "" +
	"\n" +
	"\x18events/akamai-info.proto\">\n" +
	"\x06Akamai\x12 \n" +
	"\vcountryCode\x18\x01 \x01(\tR\vcountryCode\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04cityB6\n" +
	"\x1bcom.hifx.lens.events.serverB\vAkamaiProtoZ\n" +
	".;protobufb\x06proto3"

var (
	file_events_akamai_info_proto_rawDescOnce sync.Once
	file_events_akamai_info_proto_rawDescData []byte
)

func file_events_akamai_info_proto_rawDescGZIP() []byte {
	file_events_akamai_info_proto_rawDescOnce.Do(func() {
		file_events_akamai_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_akamai_info_proto_rawDesc), len(file_events_akamai_info_proto_rawDesc)))
	})
	return file_events_akamai_info_proto_rawDescData
}

var file_events_akamai_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_akamai_info_proto_goTypes = []any{
	(*Akamai)(nil), // 0: Akamai
}
var file_events_akamai_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_akamai_info_proto_init() }
func file_events_akamai_info_proto_init() {
	if File_events_akamai_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_akamai_info_proto_rawDesc), len(file_events_akamai_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_akamai_info_proto_goTypes,
		DependencyIndexes: file_events_akamai_info_proto_depIdxs,
		MessageInfos:      file_events_akamai_info_proto_msgTypes,
	}.Build()
	File_events_akamai_info_proto = out.File
	file_events_akamai_info_proto_goTypes = nil
	file_events_akamai_info_proto_depIdxs = nil
}
