// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: events/context.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Browser         *Browser               `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	Network         *Network               `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Performance     *Performance           `protobuf:"bytes,3,opt,name=performance,proto3" json:"performance,omitempty"`
	Device          *Device                `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	UserInteraction *UserInteraction       `protobuf:"bytes,5,opt,name=userInteraction,proto3" json:"userInteraction,omitempty"`
	Geolocation     *Geolocation           `protobuf:"bytes,6,opt,name=geolocation,proto3" json:"geolocation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_events_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetBrowser() *Browser {
	if x != nil {
		return x.Browser
	}
	return nil
}

func (x *Context) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Context) GetPerformance() *Performance {
	if x != nil {
		return x.Performance
	}
	return nil
}

func (x *Context) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *Context) GetUserInteraction() *UserInteraction {
	if x != nil {
		return x.UserInteraction
	}
	return nil
}

func (x *Context) GetGeolocation() *Geolocation {
	if x != nil {
		return x.Geolocation
	}
	return nil
}

type Browser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgent     string                 `protobuf:"bytes,1,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	ScreenSize    *ScreenSize            `protobuf:"bytes,3,opt,name=screenSize,proto3" json:"screenSize,omitempty"`
	Viewport      *Viewport              `protobuf:"bytes,4,opt,name=viewport,proto3" json:"viewport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Browser) Reset() {
	*x = Browser{}
	mi := &file_events_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Browser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Browser) ProtoMessage() {}

func (x *Browser) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Browser.ProtoReflect.Descriptor instead.
func (*Browser) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{1}
}

func (x *Browser) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Browser) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Browser) GetScreenSize() *ScreenSize {
	if x != nil {
		return x.ScreenSize
	}
	return nil
}

func (x *Browser) GetViewport() *Viewport {
	if x != nil {
		return x.Viewport
	}
	return nil
}

type ScreenSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenSize) Reset() {
	*x = ScreenSize{}
	mi := &file_events_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenSize) ProtoMessage() {}

func (x *ScreenSize) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenSize.ProtoReflect.Descriptor instead.
func (*ScreenSize) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{2}
}

func (x *ScreenSize) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenSize) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Viewport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Viewport) Reset() {
	*x = Viewport{}
	mi := &file_events_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Viewport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewport) ProtoMessage() {}

func (x *Viewport) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewport.ProtoReflect.Descriptor instead.
func (*Viewport) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{3}
}

func (x *Viewport) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Viewport) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EffectiveType string                 `protobuf:"bytes,1,opt,name=effectiveType,proto3" json:"effectiveType,omitempty"`
	Downlink      float32                `protobuf:"fixed32,2,opt,name=downlink,proto3" json:"downlink,omitempty"`
	Rtt           int32                  `protobuf:"varint,3,opt,name=rtt,proto3" json:"rtt,omitempty"`
	SaveData      bool                   `protobuf:"varint,4,opt,name=saveData,proto3" json:"saveData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_events_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{4}
}

func (x *Network) GetEffectiveType() string {
	if x != nil {
		return x.EffectiveType
	}
	return ""
}

func (x *Network) GetDownlink() float32 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *Network) GetRtt() int32 {
	if x != nil {
		return x.Rtt
	}
	return 0
}

func (x *Network) GetSaveData() bool {
	if x != nil {
		return x.SaveData
	}
	return false
}

type Performance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageLoad      *PageLoad              `protobuf:"bytes,1,opt,name=pageLoad,proto3" json:"pageLoad,omitempty"`
	ResourceCount int32                  `protobuf:"varint,2,opt,name=resourceCount,proto3" json:"resourceCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Performance) Reset() {
	*x = Performance{}
	mi := &file_events_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Performance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Performance) ProtoMessage() {}

func (x *Performance) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Performance.ProtoReflect.Descriptor instead.
func (*Performance) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{5}
}

func (x *Performance) GetPageLoad() *PageLoad {
	if x != nil {
		return x.PageLoad
	}
	return nil
}

func (x *Performance) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type PageLoad struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DomComplete              float32                `protobuf:"fixed32,1,opt,name=domComplete,proto3" json:"domComplete,omitempty"`
	LoadEventEnd             float32                `protobuf:"fixed32,2,opt,name=loadEventEnd,proto3" json:"loadEventEnd,omitempty"`
	DomInteractive           float32                `protobuf:"fixed32,3,opt,name=domInteractive,proto3" json:"domInteractive,omitempty"`
	DomContentLoadedEventEnd float32                `protobuf:"fixed32,4,opt,name=domContentLoadedEventEnd,proto3" json:"domContentLoadedEventEnd,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PageLoad) Reset() {
	*x = PageLoad{}
	mi := &file_events_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageLoad) ProtoMessage() {}

func (x *PageLoad) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageLoad.ProtoReflect.Descriptor instead.
func (*PageLoad) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{6}
}

func (x *PageLoad) GetDomComplete() float32 {
	if x != nil {
		return x.DomComplete
	}
	return 0
}

func (x *PageLoad) GetLoadEventEnd() float32 {
	if x != nil {
		return x.LoadEventEnd
	}
	return 0
}

func (x *PageLoad) GetDomInteractive() float32 {
	if x != nil {
		return x.DomInteractive
	}
	return 0
}

func (x *PageLoad) GetDomContentLoadedEventEnd() float32 {
	if x != nil {
		return x.DomContentLoadedEventEnd
	}
	return 0
}

type Device struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeviceMemory        float32                `protobuf:"fixed32,1,opt,name=deviceMemory,proto3" json:"deviceMemory,omitempty"`
	HardwareConcurrency int32                  `protobuf:"varint,2,opt,name=hardwareConcurrency,proto3" json:"hardwareConcurrency,omitempty"`
	Platform            string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Vendor              string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	CookieEnabled       bool                   `protobuf:"varint,5,opt,name=cookieEnabled,proto3" json:"cookieEnabled,omitempty"`
	TouchPoints         int32                  `protobuf:"varint,6,opt,name=touchPoints,proto3" json:"touchPoints,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_events_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{7}
}

func (x *Device) GetDeviceMemory() float32 {
	if x != nil {
		return x.DeviceMemory
	}
	return 0
}

func (x *Device) GetHardwareConcurrency() int32 {
	if x != nil {
		return x.HardwareConcurrency
	}
	return 0
}

func (x *Device) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Device) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Device) GetCookieEnabled() bool {
	if x != nil {
		return x.CookieEnabled
	}
	return false
}

func (x *Device) GetTouchPoints() int32 {
	if x != nil {
		return x.TouchPoints
	}
	return 0
}

type UserInteraction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clicks        int32                  `protobuf:"varint,1,opt,name=clicks,proto3" json:"clicks,omitempty"`
	ScrollDepth   float32                `protobuf:"fixed32,2,opt,name=scrollDepth,proto3" json:"scrollDepth,omitempty"`
	TimeOnPage    float32                `protobuf:"fixed32,3,opt,name=timeOnPage,proto3" json:"timeOnPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInteraction) Reset() {
	*x = UserInteraction{}
	mi := &file_events_context_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInteraction) ProtoMessage() {}

func (x *UserInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInteraction.ProtoReflect.Descriptor instead.
func (*UserInteraction) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{8}
}

func (x *UserInteraction) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *UserInteraction) GetScrollDepth() float32 {
	if x != nil {
		return x.ScrollDepth
	}
	return 0
}

func (x *UserInteraction) GetTimeOnPage() float32 {
	if x != nil {
		return x.TimeOnPage
	}
	return 0
}

type Geolocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geolocation) Reset() {
	*x = Geolocation{}
	mi := &file_events_context_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geolocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geolocation) ProtoMessage() {}

func (x *Geolocation) ProtoReflect() protoreflect.Message {
	mi := &file_events_context_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geolocation.ProtoReflect.Descriptor instead.
func (*Geolocation) Descriptor() ([]byte, []int) {
	return file_events_context_proto_rawDescGZIP(), []int{9}
}

func (x *Geolocation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Geolocation) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_events_context_proto protoreflect.FileDescriptor

const file_events_context_proto_rawDesc = "" +
	"\n" +
	"\x14events/context.proto\"\x8e\x02\n" +
	"\aContext\x12\"\n" +
	"\abrowser\x18\x01 \x01(\v2\b.BrowserR\abrowser\x12\"\n" +
	"\anetwork\x18\x02 \x01(\v2\b.NetworkR\anetwork\x12.\n" +
	"\vperformance\x18\x03 \x01(\v2\f.PerformanceR\vperformance\x12\x1f\n" +
	"\x06device\x18\x04 \x01(\v2\a.DeviceR\x06device\x12:\n" +
	"\x0fuserInteraction\x18\x05 \x01(\v2\x10.UserInteractionR\x0fuserInteraction\x12.\n" +
	"\vgeolocation\x18\x06 \x01(\v2\f.GeolocationR\vgeolocation\"\x97\x01\n" +
	"\aBrowser\x12\x1c\n" +
	"\tuserAgent\x18\x01 \x01(\tR\tuserAgent\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12+\n" +
	"\n" +
	"screenSize\x18\x03 \x01(\v2\v.ScreenSizeR\n" +
	"screenSize\x12%\n" +
	"\bviewport\x18\x04 \x01(\v2\t.ViewportR\bviewport\":\n" +
	"\n" +
	"ScreenSize\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"8\n" +
	"\bViewport\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"y\n" +
	"\aNetwork\x12$\n" +
	"\reffectiveType\x18\x01 \x01(\tR\reffectiveType\x12\x1a\n" +
	"\bdownlink\x18\x02 \x01(\x02R\bdownlink\x12\x10\n" +
	"\x03rtt\x18\x03 \x01(\x05R\x03rtt\x12\x1a\n" +
	"\bsaveData\x18\x04 \x01(\bR\bsaveData\"Z\n" +
	"\vPerformance\x12%\n" +
	"\bpageLoad\x18\x01 \x01(\v2\t.PageLoadR\bpageLoad\x12$\n" +
	"\rresourceCount\x18\x02 \x01(\x05R\rresourceCount\"\xb4\x01\n" +
	"\bPageLoad\x12 \n" +
	"\vdomComplete\x18\x01 \x01(\x02R\vdomComplete\x12\"\n" +
	"\floadEventEnd\x18\x02 \x01(\x02R\floadEventEnd\x12&\n" +
	"\x0edomInteractive\x18\x03 \x01(\x02R\x0edomInteractive\x12:\n" +
	"\x18domContentLoadedEventEnd\x18\x04 \x01(\x02R\x18domContentLoadedEventEnd\"\xda\x01\n" +
	"\x06Device\x12\"\n" +
	"\fdeviceMemory\x18\x01 \x01(\x02R\fdeviceMemory\x120\n" +
	"\x13hardwareConcurrency\x18\x02 \x01(\x05R\x13hardwareConcurrency\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12$\n" +
	"\rcookieEnabled\x18\x05 \x01(\bR\rcookieEnabled\x12 \n" +
	"\vtouchPoints\x18\x06 \x01(\x05R\vtouchPoints\"k\n" +
	"\x0fUserInteraction\x12\x16\n" +
	"\x06clicks\x18\x01 \x01(\x05R\x06clicks\x12 \n" +
	"\vscrollDepth\x18\x02 \x01(\x02R\vscrollDepth\x12\x1e\n" +
	"\n" +
	"timeOnPage\x18\x03 \x01(\x02R\n" +
	"timeOnPage\"7\n" +
	"\vGeolocation\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04codeB7\n" +
	"\x1bcom.hifx.lens.events.clientB\fContextProtoZ\n" +
	".;protobufb\x06proto3"

var (
	file_events_context_proto_rawDescOnce sync.Once
	file_events_context_proto_rawDescData []byte
)

func file_events_context_proto_rawDescGZIP() []byte {
	file_events_context_proto_rawDescOnce.Do(func() {
		file_events_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_context_proto_rawDesc), len(file_events_context_proto_rawDesc)))
	})
	return file_events_context_proto_rawDescData
}

var file_events_context_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_events_context_proto_goTypes = []any{
	(*Context)(nil),         // 0: Context
	(*Browser)(nil),         // 1: Browser
	(*ScreenSize)(nil),      // 2: ScreenSize
	(*Viewport)(nil),        // 3: Viewport
	(*Network)(nil),         // 4: Network
	(*Performance)(nil),     // 5: Performance
	(*PageLoad)(nil),        // 6: PageLoad
	(*Device)(nil),          // 7: Device
	(*UserInteraction)(nil), // 8: UserInteraction
	(*Geolocation)(nil),     // 9: Geolocation
}
var file_events_context_proto_depIdxs = []int32{
	1, // 0: Context.browser:type_name -> Browser
	4, // 1: Context.network:type_name -> Network
	5, // 2: Context.performance:type_name -> Performance
	7, // 3: Context.device:type_name -> Device
	8, // 4: Context.userInteraction:type_name -> UserInteraction
	9, // 5: Context.geolocation:type_name -> Geolocation
	2, // 6: Browser.screenSize:type_name -> ScreenSize
	3, // 7: Browser.viewport:type_name -> Viewport
	6, // 8: Performance.pageLoad:type_name -> PageLoad
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_events_context_proto_init() }
func file_events_context_proto_init() {
	if File_events_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_context_proto_rawDesc), len(file_events_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_context_proto_goTypes,
		DependencyIndexes: file_events_context_proto_depIdxs,
		MessageInfos:      file_events_context_proto_msgTypes,
	}.Build()
	File_events_context_proto = out.File
	file_events_context_proto_goTypes = nil
	file_events_context_proto_depIdxs = nil
}
