// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: events/page.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          string                 `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pathname      string                 `protobuf:"bytes,3,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Referrer      string                 `protobuf:"bytes,4,opt,name=referrer,proto3" json:"referrer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_events_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_events_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_events_page_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *Page) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Page) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *Page) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

var File_events_page_proto protoreflect.FileDescriptor

const file_events_page_proto_rawDesc = "" +
	"\n" +
	"\x11events/page.proto\"n\n" +
	"\x04Page\x12\x12\n" +
	"\x04href\x18\x01 \x01(\tR\x04href\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\bpathname\x18\x03 \x01(\tR\bpathname\x12\x1a\n" +
	"\breferrer\x18\x04 \x01(\tR\breferrerB4\n" +
	"\x1bcom.hifx.lens.events.clientB\tPageProtoZ\n" +
	".;protobufb\x06proto3"

var (
	file_events_page_proto_rawDescOnce sync.Once
	file_events_page_proto_rawDescData []byte
)

func file_events_page_proto_rawDescGZIP() []byte {
	file_events_page_proto_rawDescOnce.Do(func() {
		file_events_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_page_proto_rawDesc), len(file_events_page_proto_rawDesc)))
	})
	return file_events_page_proto_rawDescData
}

var file_events_page_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_page_proto_goTypes = []any{
	(*Page)(nil), // 0: Page
}
var file_events_page_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_page_proto_init() }
func file_events_page_proto_init() {
	if File_events_page_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_page_proto_rawDesc), len(file_events_page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_page_proto_goTypes,
		DependencyIndexes: file_events_page_proto_depIdxs,
		MessageInfos:      file_events_page_proto_msgTypes,
	}.Build()
	File_events_page_proto = out.File
	file_events_page_proto_goTypes = nil
	file_events_page_proto_depIdxs = nil
}
