// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: events/user.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           string                 `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Did           string                 `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	Sid           string                 `protobuf:"bytes,3,opt,name=sid,proto3" json:"sid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_events_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_events_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_events_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *User) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *User) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

var File_events_user_proto protoreflect.FileDescriptor

const file_events_user_proto_rawDesc = "" +
	"\n" +
	"\x11events/user.proto\"<\n" +
	"\x04User\x12\x10\n" +
	"\x03aid\x18\x01 \x01(\tR\x03aid\x12\x10\n" +
	"\x03did\x18\x02 \x01(\tR\x03did\x12\x10\n" +
	"\x03sid\x18\x03 \x01(\tR\x03sidB4\n" +
	"\x1bcom.hifx.lens.events.clientB\tUserProtoZ\n" +
	".;protobufb\x06proto3"

var (
	file_events_user_proto_rawDescOnce sync.Once
	file_events_user_proto_rawDescData []byte
)

func file_events_user_proto_rawDescGZIP() []byte {
	file_events_user_proto_rawDescOnce.Do(func() {
		file_events_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_user_proto_rawDesc), len(file_events_user_proto_rawDesc)))
	})
	return file_events_user_proto_rawDescData
}

var file_events_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_user_proto_goTypes = []any{
	(*User)(nil), // 0: User
}
var file_events_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_user_proto_init() }
func file_events_user_proto_init() {
	if File_events_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_user_proto_rawDesc), len(file_events_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_user_proto_goTypes,
		DependencyIndexes: file_events_user_proto_depIdxs,
		MessageInfos:      file_events_user_proto_msgTypes,
	}.Build()
	File_events_user_proto = out.File
	file_events_user_proto_goTypes = nil
	file_events_user_proto_depIdxs = nil
}
